name: foodiq
description: "FoodIQ mobile application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.5.0
  http: ^1.2.1
  fl_chart: ^0.66.0
  flutter_local_notifications: ^17.0.0

  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
